# Generated by Django 4.1 on 2022-08-25 20:00

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_image_options_image_my_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='content',
            field=tinymce.models.HTMLField(default=models.TextField(verbose_name='Описание')),
        ),
    ]
